version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8
    working_directory: /home/ubuntu/bcf-webapp
    steps:
      - checkout
      - run:
          name: Create Directory Report
          command: mkdir -p /home/ubuntu/bcf-webapp/artifacts
      - run:
          name: Setup Dependencies
          command: npm install
