export const RECEIVE_CART_ETHBTC = 'app/home/RECEIVE_CART_ETHBTC';
export const RECEIVE_CART_BTCUSDT = 'app/home/RECEIVE_CART_BTCUSDT';
export const RECEIVE_CART_ETCBTC = 'app/home/RECEIVE_CART_ETCBTC';
export const RECEIVE_CART_ADABTC = 'app/home/RECEIVE_CART_ADABTC';
export const RECEIVE_CART_XRPBTC = 'app/home/RECEIVE_CART_XRPBTC';
export const RECEIVE_CART_BCCBTC = 'app/home/RECEIVE_CART_BCCBTC';

export const RECEIVE_COIN_HOTETH = 'app/home/RECEIVE_COIN_HOTETH';
export const RECEIVE_COIN_NASETH = 'app/home/RECEIVE_COIN_NASETH';
export const RECEIVE_COIN_ETCETH = 'app/home/RECEIVE_COIN_ETCETH';
export const RECEIVE_COIN_VETETH = 'app/home/RECEIVE_COIN_VETETH';
export const RECEIVE_COIN_ADAETH = 'app/home/RECEIVE_COIN_ADAETH';
export const RECEIVE_COIN_XRPETH = 'app/home/RECEIVE_COIN_XRPETH';
export const RECEIVE_COIN_EOSETH = 'app/home/RECEIVE_COIN_EOSETH';
export const RECEIVE_COIN_TRXETH = 'app/home/RECEIVE_COIN_TRXETH';
export const RECEIVE_COIN_ZILETH = 'app/home/RECEIVE_COIN_ZILETH';

export const RECEIVE_COIN_BTCUSDT = 'app/home/RECEIVE_COIN_BTCUSDT';
export const RECEIVE_COIN_ETCUSDT = 'app/home/RECEIVE_COIN_ETCUSDT';
export const RECEIVE_COIN_ETHUSDT = 'app/home/RECEIVE_COIN_ETHUSDT';
export const RECEIVE_COIN_EOSUSDT = 'app/home/RECEIVE_COIN_EOSUSDT';
export const RECEIVE_COIN_BCCUSDT = 'app/home/RECEIVE_COIN_BCCUSDT';
export const RECEIVE_COIN_TRXUSDT = 'app/home/RECEIVE_COIN_TRXUSDT';
export const RECEIVE_COIN_XRPUSDT = 'app/home/RECEIVE_COIN_XRPUSDT';
export const RECEIVE_COIN_ADAUSDT = 'app/home/RECEIVE_COIN_ADAUSDT';
export const RECEIVE_COIN_NEOUSDT = 'app/home/RECEIVE_COIN_NEOUSDT';

export const RECEIVE_COIN_ETCBTC = 'app/home/RECEIVE_COIN_ETCBTC';
export const RECEIVE_COIN_ETHBTC = 'app/home/RECEIVE_COIN_ETHBTC';
export const RECEIVE_COIN_EOSBTC = 'app/home/RECEIVE_COIN_EOSBTC';
export const RECEIVE_COIN_XRPBTC = 'app/home/RECEIVE_COIN_XRPBTC';
export const RECEIVE_COIN_OSTBTC = 'app/home/RECEIVE_COIN_OSTBTC';
export const RECEIVE_COIN_XLMBTC = 'app/home/RECEIVE_COIN_XLMBTC';
export const RECEIVE_COIN_BCCBTC = 'app/home/RECEIVE_COIN_BCCBTC';
export const RECEIVE_COIN_LTCBTC = 'app/home/RECEIVE_COIN_LTCBTC';
export const RECEIVE_COIN_ADABTC = 'app/home/RECEIVE_COIN_ADABTC';
